### PR TITLE
#36 Accept and Reject Candidates

### PR DESCRIPTION
**Pull request by WGierke**
This pull request is based on #88 and also blocked by it. The buttons, that have been added in this PR, now also get a functionality (that still needs to be implemented in the back-end).

## Description
You can find the "raw" changes between PR #88 and this PR [here](https://github.com/WGierke/concept-to-clinic/compare/35_list_candidates...WGierke:36_accept_reject_candidates?expand=1) which might be easier to oversee.
I added two methods that are invoked when the Dismiss / Mark Concerning buttons are clicked. The functions receive the ID of the candidate as soon as the user triggers the buttons. The entire page's results are not aggregated.

## Reference to official issue
This addresses #36 .

## Motivation and Context
The end-user should be able to specify whether candidates might be concerning or whether they can simply be dismissed.

## How Has This Been Tested?
I fixed the creation of candidates (before, there was an error stating that the serializer can't handle nested `create` calls) and created three candidates. I clicked the Dismiss and Mark buttons of candidates 1 and 3 and was ably to verify the correct API responses in the console:
screenshot from 2017-09-05 23-25-23

## CLA
- [X] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by lamby** [comment]
And another with merge conflicts! Alas :(

**Comment by WGierke** [comment]
And resolved :)

**Comment by lamby** [comment]
@WGierke Can you rebase against master instead of merging next time? No need to introduce all these ugly merges which don't really represent anything truly meaningful. I can do this for this PR however, 1 sec...

**Comment by lamby** [comment]
Thanks!

**Pull request merged**
