### PR TITLE
Add links to project structure documentation

### PR DESCRIPTION
**Pull request by JasonAizkalns**
## Description

Adds links to the project structure documentation.

## Reference to official issue

Addresses issue #15 

## Motivation and Context

Turns the references to the technologies into useful links to those technologies.

## How Has This Been Tested?

Clicked on links.

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
Hi @JasonAizkalns thanks for the PR! It appears some of the links you've added have stray spaces in them, e.g., `[ Title](link )`. Would you mind tidying those up? Also, MD formatted links apparently don't work inside tables. Not sure the best way approach that. Maybe inlining html would work? Ideas @lamby?

**Comment by JasonAizkalns** [comment]
Thank you @reubano. Let me know if cleaning the whitespace and hanging parentheses changes things for the MD formatted links. Interestingly enough, when I use [atom](https://atom.io/) and the [markdown preview package](https://github.com/atom/markdown-preview) things look fine on my end (see [screenshot](http://i.imgur.com/CkZeIFa.png?1)). If that still doesn't work, I'll try the inline html approach.

Aside, do you know where to find the PR template? It's mentioned in a few places, but I have not come across the appropriate formatting?

Finally, please note that I am still getting used to contributing to repos that are not my own, so I apologize for what's likely a messy commit (the `.dcm` files flooding my workspace?)

**Comment by lamby** [comment]
Hm, this PR/commit seems to add a bunch of git-lfs related files which appears to be a mistake (or is not otherwise documented...)

**Comment by reubano** [comment]
> Interestingly enough, when I use atom and the markdown preview package things looks fine:

That is weird, maybe it's an issue with [GHFMD](https://github.com/JasonAizkalns/concept-to-clinic/blob/8391d6dcd337b90129e06c818edc31b40f0bf566/docs/project-structure.md).

screen shot 2017-08-17 at 5 24 28 pm

**Comment by reubano** [comment]
> apologize for what's likely a messy commit (the .dcm files flooding my workspace?)

hmm, looks like commit #ed1693f00 is the culprit. Try a `git rebase -i master` to see if you can clean it up.

**Comment by lamby** [comment]
@JasonAizkalns Can you rebase this branch and remove the .dcm / git-lfs changes? :)

**Comment by JasonAizkalns** [comment]
@lamby and @reubano I believe the `rebase` worked and I was able to drop #ed1693f00. I did not bother to reformat the links as inline html until we can confirm that the issue is specific to GHFMD.

**Comment by reubano** [comment]
>  did not bother to reformat the links as inline html until we can confirm that the issue is specific to GHFMD.
@lamby any chance you can verify that the links look good in the build?

**Comment by lamby** [comment]
@JasonAizkalns  @reubano 

They don't render here for me, alas. Dumb question, but can't we just use `<a/>` links?

**Comment by lamby** [comment]
@JasonAizkalns I see you pushed a change to move to `<a/>` in https://github.com/concept-to-clinic/concept-to-clinic/pull/56/commits/f8b2095b172a19012879dc82828d5dae597463e3

How come we went with the markdown ones in the first place? Just curious how you tested this? :)

**Comment by lamby** [comment]
@JasonAizkalns Friendly ping on this? :)

**Comment by JasonAizkalns** [comment]
@lamby I had simply tested using the MD preview package in atom. Attempted testing with `make` but no success. At this point, probably worth closing this request and using @eltonlaw https://github.com/concept-to-clinic/concept-to-clinic/pull/64 which is more complete (spelling errors, tree corrections) and appropriately tested.

**Comment by lamby** [comment]
> probably worth closing this request and using @eltonlaw #64 which is more complete (spelling errors, tree corrections) and appropriately tested.

Elton, what say you? You closed #64, but do you want to try and put something together with this one?

**Comment by eltonlaw** [comment]
Sure, I'll reopen the old pull request. Are there any changes you want to add to the current commit?

**Comment by lamby** [comment]
@eltonlaw wrote:

> Are there any changes you want to add to the current commit?

Not that I can immediately see, no :)

Thanks!

**Comment by lamby** [comment]
Hey all, what's this blocking on? Should I be looking for another commit/PR/issue? :)

Best wishes,

— Chris

**Comment by lamby** [comment]
Chris Lamb wrote:

> Hey all, what's this blocking on? Should I be looking for another commit/PR/issue? :)

@eltonlaw @JasonAizkalns @reubano   ^^ ;)

**Comment by reubano** [comment]
@lamby... #83 should supersede this PR. I guess we can leave this one open until the other is merged.

**Comment by lamby** [comment]
@reubano Okay, am assigning to you. :)

**Comment by reubano** [comment]
superseded by #83

**Pull request closed without merging**
