### PR TITLE
#15 - Add links to the project structure documentation

### PR DESCRIPTION
**Pull request by eltonlaw**
## Description

(resubmission of PR#64 - couldn't just reopen it cause I deleted the old fork and there was some weird merging thing going on)

Hi, I've added links for everything below. There weren't any explicit instructions on where to link so I just linked to the documentation home for the most part. On some occasions, I would link to a specific part of the documentation (Django Migrations, Docker Containers etc.):

* Docker
* docker-compose
* sphinx
* Django
* Django Rest Framework
* Vue.js
* Django database migrations
* requirements.txt
* DICOM
* git-lfs
* Flask
* flake8

Links not added (there didn't seem to be any place to put them, advice?):

* pip
* pytest

Oh yea, while I was looking through it I found some minor typos so I also added those changes.
## Reference to official issue

#15 - Add links to the project structure documentation

## How Has This Been Tested?

I tested with make html and it built with no error. I also ran it and went through and clicked on each link.

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
Looks like the `style` tag isn't getting any love :). Any chance you can see how things look without it? 

```html
<style> tr:nth-child(odd) { background-color: #f6f6f6; } table#structure-table { border-collapse: separate; border-spacing: 0 5px; } </style>
```

screen shot 2017-09-01 at 12 51 22 pm

**Comment by lamby** [comment]
Hey @eltonlaw   Anything blocking on you on this? :)

**Comment by eltonlaw** [comment]
@lamby Yeah, I can't seem to run make anymore without django throwing an error. autodoc can't import stuff from `backend` because the django settings are improperly configured, it says that I need to define the environment variable `DJANGO_SETTINGS_MODULE`. Any ideas on how to fix this or bypass this, since I really only need to render the one file.

If this seems like a headache to deal with feel free to pass this issue to someone else.

**Comment by lamby** [comment]
@eltonlaw 

If you are having a specifc problem please provide full tracebacks and full error messages etc to a pastebin - the messages you are seeing are somewhat generic. However, are you sure you have created a virtualenv, followed the project setup docs, etc. etc.? :)

**Comment by eltonlaw** [comment]
Whoops sorry about that, here's the [error message](https://pastebin.com/fZcLaX0S)

Yeah I _think_ I did everything: 
* Created a virtualenv and activated it
* `pip install -r requirements.txt`
* `docker-compose -f local.yml build`
* `docker-compose -f local.yml up`. 
* `cd docs/`
* `make html`

I've tried cloning a fresh repo and running the above but I still get an error, it's a slightly different error message: [[Error Message](https://pastebin.com/ErbMb6Vh) | [Traceback](https://pastebin.com/u5qW1tmn)]

Oh by the way random note, while messing around with the installation process I get 
```
Double requirement given: sphinx_rtd_theme==0.2.4 (from -r requirements.txt (line 7)) (already in sphinx_rtd_theme==0.1.9 (from -r prediction/requirements/local.txt (line 6)), name='sphinx-rtd-theme')
```
Is this on purpose?

**Comment by lamby** [comment]
@eltonlaw 

Did you try ``DJANGO_SETTINGS_MODULE=config.settings.local make html``

> Oh by the way random note, while messing around with the installation process I get "Double requirement given"

Please file as a new issue :)

**Comment by lamby** [comment]
Please also rename this pull request ;)

**Comment by eltonlaw** [comment]
@lamby Well I tried that, it didn't work either. But I fixed it in a hacky way, I just deleted `apidoc_interface` and it builds now with `make html`, so there's that. Sorry I really should have thought of that earlier. 

Oh by the way, here's the error message when running `DJANGO_SETTINGS_MODULE=config.settings.local make html` if you want to debug it: https://pastebin.com/wxXHwJpB

@reubano Sorry for the delay here's a screenshot of how it renders without the CSS. It looks less clean imo, if the only problem is that the <style> stuff renders as text on GitHub do you want to throw it all into `_static/c2c_custom.css` adding id="structure-tr" to all <tr> tags and with the following names? 
```
tr.structure-tr:nth-child(odd) {
    ...
}
table#structure-table {
    ...
}

```

screen shot 2017-09-05 at 5 46 08 pm

**Comment by reubano** [comment]
> if the only problem is that the <style> stuff renders as text on GitHub...

Yea, I think moving the `style` tags to the css file is a great idea! Can you give it a try?

**Comment by eltonlaw** [comment]
@reubano For verification, here's how it looks running make, everything should be just as is, is this okay to merge?

screen shot 2017-09-06 at 7 00 57 pm

**Comment by reubano** [comment]
Looks good. Do you mind squashing to 1 commit?

**Comment by eltonlaw** [comment]
Uhh, how's that, I don't know if I did it correctly.

**Comment by reubano** [comment]
> Uhh, how's that, I don't know if I did it correctly.

Almost! You got the squashing down, but the commit message needs a little tweaking. You can try something like this: `git commit --amend -m "Add links to the project structure documentation"`

**Comment by eltonlaw** [comment]
sweet that worked great thanks, btw I left the rest of the old commit message in the body

**Comment by lamby** [comment]
@reubano LGTM. Not merging as assigned to thee. :)

**Pull request merged**
