### PR TITLE
Fix incorrect developer documentation link in the README

### LINKED ISSUE #46: Fix incorrect "developer documentation" link in the readme
The "developer documentation" under [Getting Started](https://github.com/concept-to-clinic/concept-to-clinic#getting-started) doesn't link to the "Local development with Docker" section.

## Expected Behavior
The link should point to https://concept-to-clinic.readthedocs.io/en/latest/developing-locally-docker.html

## Current Behavior
The link points to the main documentation page https://concepttoclinic.drivendata.org/documentation

## Possible Solution
Change the link or reword the text so that it is clear where the current link leads to.

## Steps to Reproduce
visit https://github.com/concept-to-clinic/concept-to-clinic#getting-started
click the "developer documentation" link 

## Acceptance criteria
- [ ] Readme documentation links to the correct location

### PR DESCRIPTION
**Pull request by foo-bar-baz-qux**
## Description

Changed link to point to Docker setup instructions, added another link to the main developer documentation page.

## Reference to official issue

Fixes #46.

## Motivation and Context

Documentation fix.

## How Has This Been Tested?

Tested the new links on the rendered MD page.

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by lamby** [comment]
Good spot, thank you. :+1:

**Comment by reubano** [comment]
Hi @foo-bar-baz-qux thanks for the contribution! I believe "Concept to Clinic’s documentation!" would be a more appropriate text for https://concepttoclinic.drivendata.org/documentation. "Developer documentation" is a subheading under that link, along with "Specification" and "Contribution Agreements". It doesn't seem possible to link directly to the subheadings however. The closest option I was able to see is linking to the first section of "Developer documentation" at https://concept-to-clinic.readthedocs.io/en/latest/contribute.html#getting-started.

**Comment by lamby** [comment]
Assigning @foo-bar-baz-qux  :)

**Comment by foo-bar-baz-qux** [comment]
Makes sense, I've updated the link text, cheers.

**Comment by reubano** [comment]
Looks good @foo-bar-baz-qux. Do you mind rebasing to master?

**Comment by foo-bar-baz-qux** [comment]
No problem, should be rebased to master now.

**Comment by lamby** [comment]
Thanks!

**Pull request merged**
