### PR TITLE
Add default githooks for tests and flake8

### PR DESCRIPTION
**Pull request by musale**
## Description
I have implemented a githook-pre-commit file that has the `flake8` commands for styling and the command to run tests in the docker containers locally.

## Reference to official issue
It meets requirements for #42 

## Motivation and Context

This change will allow developers to run flake8 and tests before creating a commit. Flake8 command currently runs on uncommitted and staged python files with changes. This reduces the number of files that will be checked against before a commit. In case of project-wide checks, it could be done at CI level.

Documentation on how to set this up locally has also been included.

## How Has This Been Tested?
* Remove any existing `pre-commit` files in `.git/hooks` folder i.e. `rm .git/hooks/pre-commit`
* Copy the .githooks-pre-commit file into `.git/hooks/` as `pre-commit`
* Make it executable using `chmod +x .git/hooks/pre-commit`
* Run `.git/hooks/pre-commit` to test the commands
* Make a change in the code base, add and commit it. It should run `flake8` and run the tests before committing. If the commands pass, the commit is created otherwise it is not.
**Note:**  the tests will fail from the current master branch due to #50 . If you patch your code with https://github.com/concept-to-clinic/concept-to-clinic/pull/50 it should pass all tests

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
Hi @musale thanks for your contribution! Can you please commit the executable version? That would simplify the installation instructions a bit. Also, could you modify the part about copying the file to use `cp -f` with a note that this will automatically overwrite any existing hook? Thanks!

**Comment by reubano** [comment]
Just to clarify, with the above changes you can then remove the following steps from the instructions.

```bash
 +To remove any initial `pre-commit` files, you run:
 +    $ rm .git/hooks/pre-commit
 +
 +Make the `.git/hooks/pre-commit` file executable by running:
 +
 +    $ chmod +x .git/hooks/pre-commit
```

**Comment by musale** [comment]
Hi @reubano I have effected the proposed changes.

**Comment by reubano** [comment]
Hi @musale, I've gone ahead and rebase a squashed version of this PR. FYI, I'll force push to update this branch so that it shows up here on github as merged. Thanks!

**Comment by reubano** [comment]
Hi @musale turns out I couldn't rebase on your behalf :(. Are you ok rebasing to master and squashing everything to one commit? Thanks!

**Comment by musale** [comment]
Hey @reubano will that do?

**Comment by reubano** [comment]
Thanks for the PR @musale. Next time, can you please *also* `rebase` to master as well?

**Comment by musale** [comment]
Gotcha @reubano 👍

**Pull request merged**
