### PR TITLE
Allow to select slice

### PR DESCRIPTION
**Pull request by vessemer**
At this moment only slide preview was available, this PR allows selecting the desired slice from a list by clicking on its name. 

## Reference to official issue  
It also fixes issue #241 

## Screenshots (if appropriate):
peek 2017-11-21 13-35

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by Serhiy-Shekhovtsov** [comment]
This fixed #241, as well right?

**Comment by lamby** [comment]
Thanks! :)

**Comment by vessemer** [comment]
peek 2017-11-22 01-11

**Comment by lamby** [comment]
Merged, thank you.

**Pull request merged**
