### PR TITLE
#20 Document the Julian de Wit algorithm

### PR DESCRIPTION
**Pull request by WGierke**
I added an initial documentation of the Julian de Wit algorithm. The algorithm output was ensembled with the results of the [Daniel Hammack algorithm](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/docs/algorithm_hammack.md).

## Reference to official issue
This pull request addresses #20 

## Motivation and Context
At some point we need to implement an algorithm that can segment the nodules and detect whether they are malicious or not. It makes sense to first evaluate the top 10 solutions for the Data Science Bowl 2017 regarding how performant they are and how easy it would be to use them in our application. 

## CLA
- [X] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by WGierke** [comment]
@timothyman Do you want to add any insights you talked about in PR #99 ? We'd highly appreciate it :)

**Comment by timothyman** [comment]
@WGierke, sure. Unfortunately I wasn't joking when I said I needed a new harddisk before I can start to run the models and I'm out of town for the next 2 weeks without my DL box. So feel free to merge into master now. 

On a first glance I noticed you probably missed some dependencies, ```scikit-image``` and ```lxml```. Can you maybe take a look at my branch? I should have the complete list in the markdown file. Same location. 

Also, I have seen that in order to get it running on Linux, you will have to remove and replace the dependency on ```ntpath``` with ```os.path``` in the step3 file. If I am not mistaken Python will handle this dependency automatically, so it should still work on Windows.

If I find anything else later I will create a new issue. Great writeups so far. Hope I can write one soon too.

**Comment by WGierke** [comment]
@timothyman Thanks a lot :) It looks way nicer with such detailed dependency versions!
Oh I see :D I also didn't manage to run an algorithm so far because my internet connection always aborts before I finish downloading the whole training sets ...

**Comment by reubano** [comment]
Thanks @WGierke! LGTM. As you noted in #105, the tests recently broke. However, as this is just adding documentation, it should be fine to merge. Would you mind squashing to 1 commit now?

**Comment by WGierke** [comment]
@reubano Alright, I squashed everything including the work of @timothyman into one commit.

**Pull request merged**
