### PR TITLE
#18 Document the grt123 algorithm

### PR DESCRIPTION
**Pull request by WGierke**
I added an initial documentation of the grt123 algorithm. As soon as I have some specs on how long the prediction takes, I'll replace the TODOs. Please feel free to add commits and extend it!

## Reference to official issue
This pull request addresses #18 .

## Motivation and Context
At some point we need to implement an algorithm that can segment the nodules and detect whether they are malicious or not. It makes sense to first evaluate the top 10 solutions for the Data Science Bowl 2017 regarding how performant they are and how easy it would be to use them in our application. 

## CLA
- [X] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
Nice writeup! My only concern is the ability to run on a CPU. In familiarizing myself with the DSB, I [attempted to port](https://github.com/concept-to-clinic/DSB2017) this algorithm to Python 3. In the process I encountered several hurdles when also attempting to run on a CPU. You can see some of the changes I made [such as this](https://github.com/concept-to-clinic/DSB2017/blob/877622c3c18fb48c8004e0afb8472f916a9d3277/predict/__init__.py#L52) in the [conversion branch](https://github.com/concept-to-clinic/DSB2017/tree/conversion).

**Comment by WGierke** [comment]
Thanks for your feedback! I'm not familiar with pyTorch at all but I would have never thought that it's so complicated to port it to Python 3 enable it to run on a CPU... In that case I should clearly update the relevant parts of the algorithm documentation about that. DId you happen to try how long it takes the model to predict the cancer probability on one image?

**Comment by reubano** [comment]
> Did you happen to try how long it takes the model to predict the cancer probability on one image?

I ran the prediction algo on the sample image set in a AWS p2 instance. I don't rem the timings exactly. Maybe a few mins. Didn't do so for a single image since the repo wasn't set up to work that way.

**Comment by reubano** [comment]
Hi @WGierke any luck updating the CPU portion? In particular, the section that says `It already is possible to use the model on both CPU and GPU.` should be modified to address the issues that may be encountered when porting to run on a CPU (such as `DataParallel`).

**Comment by reubano** [comment]
:shipit:

**Comment by WGierke** [comment]
Hey @reubano unfortunately I had no success so far, sorry. Nevertheless, I updated the relevant sections based on your remarks.

**Comment by reubano** [comment]
No problem!

**Pull request merged**
