### PR TITLE
fixed candidate select\deselect API test

### PR DESCRIPTION
**Pull request by Serhiy-Shekhovtsov**
Small fix of the candidates API tests based on this [discussion](https://github.com/concept-to-clinic/concept-to-clinic/pull/254#issuecomment-348448307).

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
The test failed. Re-running to see if that does anything.

**Comment by lamby** [comment]
Still failing..

**Comment by Serhiy-Shekhovtsov** [comment]
@reubano, @lamby I have solved conflicts and solved one issue with my test. I can see that build is still failing but can't see how this is related to my changes. All failing tests are failing by timeout and called from `test_endpoints`.

**Comment by lamby** [comment]
Thanks, okaley. (Is there an issue for this other, failing, test?)

**Comment by Serhiy-Shekhovtsov** [comment]
@lamby maybe I am missing something, what test do you mean?

**Comment by Serhiy-Shekhovtsov** [comment]
@lamby, @reubano tests fixed.

**Comment by lamby** [comment]
Many thanks @Serhiy-Shekhovtsov  :)

**Pull request merged**
