### PR TITLE
Chose an appropriate DATA_SHAPE

### PR DESCRIPTION
**Pull request by vessemer**
Uncommented tests, as was mentioned in [this](https://github.com/concept-to-clinic/concept-to-clinic/pull/298#pullrequestreview-92612801) comment.

## CLA
- [x] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well

### CODE REVIEW

**Comment by reubano** [comment]
Various `memory error`s. Restarted the build to see if that helps.

**Comment by vessemer** [comment]
@reubano, It happens time to time 'cause of unreasonably large choice of the [`DATA_SHAPE`](https://github.com/concept-to-clinic/concept-to-clinic/commit/06117fb72b1bf03ad8b522d2f9e42af1b6711a2c#diff-638bbca55ea01b2d5eeb28b7e52321eeR21). The average maximum height of lungs for a grown man, according to [this research](https://www.researchgate.net/profile/Kevin_Capello/publication/221873867_Linear_dimensions_and_volumes_of_human_lungs_obtained_from_CT_images/links/5a1d79daaca2726120b2c4b5/Linear-dimensions-and-volumes-of-human-lungs-obtained-from-CT-images.pdf) (Table 2), is 282mm with std equals to 22mm and median 274mm (Table 2). Assuming normal distribution, [3 sigmas](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule) aside the mean will lead to the probability of case `h` belong to the interval `P{|282 - h| <= 66} ~= 0.9974`. Taking into an account the fact that all algorithms which were described (not only implemented ones) works with spacing on z-axis >= 0.9, therefore, having an upper bound value of `(282 + 66) / 0.9 = 386` for z-axis should be enough for all cases.

**Comment by vessemer** [comment]
I've made `DATA_SHAPE` to be `(512, 512, 512)` which should fit in memory while having reserved space for the z-axis.

**Comment by vessemer** [comment]
@reubano, done!

**Comment by lamby** [comment]
Can you clarify what you mean by "active" here? :)

**Comment by vessemer** [comment]
@lamby, initially I've created this PR to uncomment (activate) all tests, which I forget to uncomment in my previous PR #298, but then I've decided to [figure out an appropriate `DATA_SHAPE`](https://github.com/concept-to-clinic/concept-to-clinic/pull/304#issuecomment-361691349), along with other fixes, thus I've renamed this PR.

**Comment by reubano** [comment]
Great work @vessemer! I think the main issue is the inclusion of "other fixes" unrelated to `DATA_SHAPE` things. Did you just happen to notice some thing didn't look right (like the `print` statements)? Or were there some tests that were still failing?

**Comment by vessemer** [comment]
Thanks, @reubano! Let me describe in a bit more details: commit [All tests acitve](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/commits/32e002d854c9633bdc4538a89933ab60ecbe9708) is just to uncomment the commented tests, then [Codestyle of evaluate_detection.py](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/commits/e4ba764af6c6cb570fdb86efc2632eb59cbf7008) commit is merely about that some thing didn't look right, though in the last commit I've included (additional to the DATA_SHAPE things):
 - Remove redundant [`self.scale_factor`](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-7ebde87c389dab64f0c9e8a81e6b6391L40) which is neither dependend on DATA_SHAPE nor on [`self.input_shape`](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-7ebde87c389dab64f0c9e8a81e6b6391L39) by [this](https://github.com/vessemer/concept-to-clinic/blame/e4ba764af6c6cb570fdb86efc2632eb59cbf7008/prediction/src/algorithms/segment/src/models/simple_3d_model.py#L64-L73) and [this](https://github.com/vessemer/concept-to-clinic/blame/e4ba764af6c6cb570fdb86efc2632eb59cbf7008/prediction/src/algorithms/segment/src/models/simple_3d_model.py#L48-L55).
 - [calculate_volume](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-d685e97b90047b1be62100544969f8ac) function now accept centroids in real world units (mm) if meta was provided, which is logical and also leads to renewal of the [tests](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-4dac9e3a237cb8ddd0ca837da32061ce)

**Comment by reubano** [comment]
> Codestyle of evaluate_detection.py commit is merely about that some thing didn't look right, 

Does this mean it wasn't previously being caught by the code linter that travis runs?

> Remove redundant self.scale_factor which is neither dependend on DATA_SHAPE nor on self.input_shape by this and this.

This just sounds like a refactoring, so the current test set should (hopefully) be able to confirm nothing broke

> calculate_volume function now accept centroids in real world units (mm) if meta was provided, which is logical and also leads to renewal of the tests

This one looks like an enhancement. I noticed that the `x` and `z` values were swapped. Is that something specific to using mm units? Or was it a latent bug that you caught?

--

Again, overall great work! And I think we may need to split this up into at least 2 individual PRs. One addressing the `memory error` and commented out tests. 

This 1st PR could also address the codestyle as long as the current linters properly identified the problem. If not, then a 2nd PR would fix the codestyle **and** the linter.

If the `x` and `z` values swapping isn't specifically related to mm units, that should probably go in a sep PR as a bug fix. Otherwise, it can just be included in the last PR to address the mm units and the related test adjustments.

Does that make sense?

**Comment by vessemer** [comment]
> Does this mean it wasn't previously being caught by the code linter that travis runs?   

Not all of them, 'cause code linter indicate `E999 SyntaxError: invalid syntax` and not proceed after that.    
> This just sounds like a refactoring, so the current test set should (hopefully) be able to confirm nothing broke   

That's true.

> This one looks like an enhancement. I noticed that the x and z values were swapped. Is that something specific to using mm units? Or was it a latent bug that you caught?

The swap is done due to the `xyz` way to store volumetric data pushed by the PR #44.

**Comment by reubano** [comment]
Just saw your new PRs. Let's see how travis likes them :).

**Comment by vessemer** [comment]
@reubano, done by [`Rfactoring`](https://github.com/concept-to-clinic/concept-to-clinic/pull/306), [`Chose an appropriate DATA_SHAPE`](https://github.com/concept-to-clinic/concept-to-clinic/pull/307) and  [`Allows to calculate_volume in mm`](https://github.com/concept-to-clinic/concept-to-clinic/pull/308).

**Comment by vessemer** [comment]
Superceded by PRs #307 and #306

**Pull request closed without merging**
